language: php

sudo: required
dist: trusty

addons:
  chrome: stable

php:
  - 7.2

cache:
  directories:
    - "$HOME/.composer/cache/files"

before_script:
  - travis_retry composer self-update
  - chmod -R 777 bootstrap/cache/ storage/logs/
  - export DISPLAY=:99.0

script:
  - cp .env.testing .env
  - travis_retry composer update --no-interaction --no-progress --ignore-platform-reqs
  - npm install
  - npm run dev
  - php artisan key:generate
  - php artisan migrate --seed
  - php artisan passport:keys
  - php artisan storage:link
  - php artisan voyager:install
  - sh -e /etc/init.d/xvfb start
  - php artisan serve &
  - phpunit --coverage-text --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - chmod 777 deploy.sh
  - ./deploy.sh