version: 2
jobs:
  build:
    docker:
      - image: edbizarro/gitlab-ci-pipeline-php:7.2-alpine
    working_directory: /var/www/html
    steps:
      - checkout
      #- restore_cache:
      #    keys:
      #        - v1-dependencies-{{ checksum "composer.json" }}
      #        - v1-dependencies-
      - run: composer install --no-interaction
      #- save_cache:
      #    paths:
      #        - ./vendor
      #    key: v1-dependencies-{{ checksum "composer.json" }}
      - run: cp .env.testing .env
      - run: php artisan config:clear
      - run: php artisan key:generate
      - run: php artisan config:cache
      - run: php artisan migrate --seed
      - run: php artisan passport:keys
      - run:
          background: true
          command: php artisan serve
      - run: ./vendor/bin/phpunit --stop-on-error --stop-on-failure --coverage-clover=coverage.xml
      - run: bash <(curl -s https://codecov.io/bash)
  #staging:
  #  docker:
  #    - image: appropriate/curl:latest
  #  steps:
  #    - run: curl -X POST ${STAGING_DEPLOYMENT_URL}
#workflows:
#  version: 2
#  deploy:
#    jobs:
#      - build
#      - staging:
#          requires:
#            - build
#          filters:
#            branches:
#              only: master